# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4ac9e5b3ca1371c8a6c2627dfbcb29c04c8f3f5902e6a509ae2cbf8f8172bc06007e2441c12fa67137cfac851863586ed5af634a27112a7e56d3f306b16e8c7

test:
  secret_key_base: a55005edc60cb40a24ff0c86f29e489dbc93a179f1bd2892aa43dd6b9d74feb9649c981084302a8ae9d60ca832400c688e989cd9154e507ef760b3d104d1b6c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
